winzou_state_machine:
    sylius_payment:
        callbacks:
            after:
                monsieurbiz_stuart_send_job:
                    on: ["complete"]
                    do: ["@monsieurbiz.stuart_delivery.transfer.job", "sendFromOrder"]
                    args: ["object"]
